def mimetypeCheck(fileName):
    match str(fileName):
        case ".png'":
            return 'image/png'
        case '.jpg':
            return 'image/jpg'
        case ".jpeg":
            return 'image/jpeg'
        case _:
            return 1
