version: "2"

services:
  app:
    build: ./api
    links:
      - db
    ports:
      - "5000:5000"
  db:
    container_name: mydb
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
